version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html  # Mount current directory (root) to container
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost

  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html  # Mount current directory
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app